import turtle as t
t.shape('turtle')
t.pensize(4)
t.pencolor("red")
t.fillcolor("yellow")
t.speed(100)
t.goto(0,0)
t.begin_fill()
for i in range(4): #Kvadrats
    t.forward(200)
    t.left(90)
t.end_fill()
t.lt(180)
t.up()
t.goto(-50,0)
t.down()
t.pencolor("blue")
t.fillcolor('green')
t.begin_fill()
for i in range(3): #Trijsturis
    t.fd(200)
    t.lt(-120)
t.end_fill()

t.up()
t.goto(50,-50)
t.down()

t.pencolor("magenta")
t.fillcolor('brown')
t.begin_fill()
for i in range(6): #Sešsturis
    t.fd(150)
    t.lt(60)
t.end_fill()
t.up()
t.goto(0,0)
t.done()