from tkinter import *
logs = Tk()
logs.title("Skolotājs")
logs.geometry("300x600")
nos = Label(text="Ivadiet Lietotājvārds un Parole",font=('Arial',18, 'bold'))
nos.pack()
vards = Entry(font=('Arial',18, 'bold'))
vards.pack()
parole = Entry(font=('Arial',18, 'bold'),show="*")
parole.pack()
logs.mainloop()