from tkinter import *
root = Tk()
btn = Button(root, text="press me!")
btn2 = Button(root, text="Mani sauc:")
btn.config(command=lambda: print("Привет, Tkinter!"))
btn2.config(command=lambda: print("Andris"))
btn.pack(padx=120, pady=30)
btn2.pack(padx=120, pady = 20)
root.title("Мое приложение Tkinter")
root.mainloop()
