from turtle import *
#radius=int(input("radius"))
def smailik (radius):
    pu()
    goto(0,-(radius))
    pd()
    circle(radius)
    pu()
    home()
    goto(-(radius-20),-(10))
    rt(90)
    pd()
    circle((radius-20),180)
    pu()
    home()
    pensize(radius/10)
    goto(-(radius/2),(radius/2))
    pd()
    dot()
    pu()
    goto((radius/2),(radius/2))
    pd()
    dot()
    pensize(1)
    pu()
smailik(120)
smailik(140)
