import turtle
a = turtle.Turtle()
#a.shape('turtle')
a.hideturtle()
a.speed(10)
a.pencolor("blue")
a.fillcolor("blue")
a.up()
a.goto(-300,-100)
a.setheading(0)
a.down()
a.begin_fill()
a.fd(600)
a.setheading(90)
a.fd(400)
a.setheading(180)
a.fd(600)
a.setheading(270)
a.fd(400)
a.end_fill()
a.pencolor("yellow")
a.fillcolor("yellow")
def makeStar():
  heading_before_star = a.heading()
  a.setheading(0)
  a.begin_fill()
  for k in range(5):
    a.forward(20)
    a.right(144)
  a.setheading(heading_before_star)
  a.end_fill()
a.up()
a.goto(0,0)
a.down()
a.setheading(-15)
for i in range(12):
  makeStar()
  a.left(30)
  a.penup()
  a.forward(50)
  a.pendown()

turtle.mainloop()